# ── Commands ─────────────────────────────────────────────────

cmd_gen_env() {
    local NOCHECK=false
    for arg in "$@"; do
        case "$arg" in
            --nocheck)  NOCHECK=true ;;
            -h|--help)  gen_env_usage ;;
            --*)        echo "Unknown option: $arg" >&2; gen_env_usage ;;
        esac
    done

    # Determine output file
    local out_file="${DOCKYARD_ENV:-./dockyard.env}"
    if [ -f "$out_file" ]; then
        echo "Error: ${out_file} already exists. Remove it first or set DOCKYARD_ENV to a different path." >&2
        exit 1
    fi

    # Apply env var overrides or defaults
    local root="${DOCKYARD_ROOT:-/dockyard}"
    local prefix="${DOCKYARD_DOCKER_PREFIX:-dy_}"
    local pool_size="${DOCKYARD_POOL_SIZE:-24}"
    local sysbox_mgr_extra_args="${DOCKYARD_SYSBOX_MGR_EXTRA_ARGS:-${SYSBOX_MGR_EXTRA_ARGS:-}}"
    local sysbox_subid_user="${DOCKYARD_SYSBOX_SUBID_USER:-${prefix}docker}"
    local sysbox_subid_start="${DOCKYARD_SYSBOX_SUBID_START:-}"
    local sysbox_subid_count="${DOCKYARD_SYSBOX_SUBID_COUNT:-}"

    # Generate random networks if not provided via env
    local bridge_cidr="${DOCKYARD_BRIDGE_CIDR:-}"
    local fixed_cidr="${DOCKYARD_FIXED_CIDR:-}"
    local pool_base="${DOCKYARD_POOL_BASE:-}"

    if [ -z "$bridge_cidr" ] || [ -z "$fixed_cidr" ] || [ -z "$pool_base" ]; then
        local attempts=0
        local max_attempts=10

        while [ $attempts -lt $max_attempts ]; do
            attempts=$((attempts + 1))

            # Random /24 from 172.16.0.0/12 for bridge
            local b2=$(( RANDOM % 16 + 16 ))   # 16-31
            local b3=$(( RANDOM % 256 ))        # 0-255
            bridge_cidr="${DOCKYARD_BRIDGE_CIDR:-172.${b2}.${b3}.1/24}"
            fixed_cidr="${DOCKYARD_FIXED_CIDR:-172.${b2}.${b3}.0/24}"

            # Random /16 from 172.16.0.0/12 for pool (different second octet)
            local p2=$(( RANDOM % 16 + 16 ))    # 16-31
            while [ "$p2" -eq "$b2" ]; do
                p2=$(( RANDOM % 16 + 16 ))
            done
            pool_base="${DOCKYARD_POOL_BASE:-172.${p2}.0.0/16}"

            if [ "$NOCHECK" = true ]; then
                break
            fi

            local env_dir
            env_dir="$(cd "$(dirname "${out_file}")" 2>/dev/null && pwd)" || env_dir=""
            if check_subnet_conflict "$fixed_cidr" "$pool_base" 2>/dev/null && \
               check_sibling_conflict "$fixed_cidr" "$pool_base" "$env_dir" 2>/dev/null; then
                break
            fi

            # Reset for next attempt (only re-randomize what wasn't user-provided)
            [ -n "${DOCKYARD_BRIDGE_CIDR:-}" ] || bridge_cidr=""
            [ -n "${DOCKYARD_FIXED_CIDR:-}" ] || fixed_cidr=""
            [ -n "${DOCKYARD_POOL_BASE:-}" ] || pool_base=""

            if [ $attempts -eq $max_attempts ]; then
                echo "Error: Could not find non-conflicting subnets after ${max_attempts} attempts." >&2
                echo "Provide explicit values via DOCKYARD_BRIDGE_CIDR, DOCKYARD_FIXED_CIDR, DOCKYARD_POOL_BASE." >&2
                exit 1
            fi
        done
    else
        # All three provided explicitly — validate unless --nocheck
        if [ "$NOCHECK" = false ]; then
            check_subnet_conflict "$fixed_cidr" "$pool_base" || exit 1
        fi
    fi

    # Validate all CIDRs are in RFC 1918 private ranges
    check_private_cidr "$bridge_cidr" "DOCKYARD_BRIDGE_CIDR" || exit 1
    check_private_cidr "$fixed_cidr"  "DOCKYARD_FIXED_CIDR"  || exit 1
    check_private_cidr "$pool_base"   "DOCKYARD_POOL_BASE"   || exit 1

    # Conflict checks (unless --nocheck)
    if [ "$NOCHECK" = false ]; then
        check_prefix_conflict "$prefix" || exit 1
        check_root_conflict "$root" || exit 1
    fi

    if [ -n "${sysbox_subid_start}${sysbox_subid_count}" ]; then
        if [ -z "$sysbox_subid_start" ] || [ -z "$sysbox_subid_count" ]; then
            echo "Error: DOCKYARD_SYSBOX_SUBID_START and DOCKYARD_SYSBOX_SUBID_COUNT must be set together." >&2
            exit 1
        fi
        validate_uint "$sysbox_subid_start" "DOCKYARD_SYSBOX_SUBID_START" || exit 1
        validate_uint "$sysbox_subid_count" "DOCKYARD_SYSBOX_SUBID_COUNT" || exit 1
    fi

    local quoted_sysbox_mgr_extra_args
    printf -v quoted_sysbox_mgr_extra_args '%q' "$sysbox_mgr_extra_args"

    # Write config file
    cat > "$out_file" <<EOF
# Dockyard configuration
# Generated by: dockyard.sh gen-env

DOCKYARD_ROOT=${root}
DOCKYARD_DOCKER_PREFIX=${prefix}
DOCKYARD_BRIDGE_CIDR=${bridge_cidr}
DOCKYARD_FIXED_CIDR=${fixed_cidr}
DOCKYARD_POOL_BASE=${pool_base}
DOCKYARD_POOL_SIZE=${pool_size}

# Optional sysbox controls. Extra args are split on whitespace and appended to sysbox-mgr.
DOCKYARD_SYSBOX_MGR_EXTRA_ARGS=${quoted_sysbox_mgr_extra_args}

# Optional deterministic /etc/subuid and /etc/subgid reservation.
# Set START and COUNT together to have create replace this user's range.
DOCKYARD_SYSBOX_SUBID_USER=${sysbox_subid_user}
DOCKYARD_SYSBOX_SUBID_START=${sysbox_subid_start}
DOCKYARD_SYSBOX_SUBID_COUNT=${sysbox_subid_count}
EOF

    echo "Generated ${out_file}:"
    echo ""
    cat "$out_file"
}
